### ISSUE TITLE
Building the project

### ISSUE THREAD

**Issue by MaFrance351** [hatwheels/pos_ingenico_220_250_arkanoid#1]
How can I add these code into the Telium project? 
I have thes Telium SDKs and IngeDev IDE but there is absolutely no documentation for it.

**Comment by hatwheels** [comment]
Hello,

These are proprietary and not open-source friendly. Also  You won't find any manual or documentation readily available, unless you buy an Ingenico POS from an official sale channel. There are some powerpoint presentations available online that provide information some information about the structure of the SDK and setting up the POS and project.

I don't have any of that information available myself as I'm not affiliated with Sagem (the company that developed Telium). I was programming Ingenico POS at a job many years ago and that's where I made this in my spare time.

**Comment by hatwheels** [comment]
@MaFrance351 I've updated the README with this information.

**Comment by MaFrance351** [comment]
Could you upload the whole project of the IngeDev that I can compile winh Ingenico SDK?

**Comment by hatwheels** [comment]
Sorry, I don't have any personal project. The released project you are mentioning is not owned by me. but by the company I worked at. Nor do I have any copy of it. You'll have to read the available information online and create a Telium project.
